### ISSUE TITLE
Debug testgithub repo

### ISSUE THREAD

**Issue by jasnow** [jennytech/testgithub#1]
Moving https://github.com/sporkrb/spork-rails/issues/27 here.

Questions
1. Why are you using Rails 5? I suggest using 4.2.6.
2. Suggest getting your testing (rake command) running first. Remove/hid code if needed to get stable version then add it back.

**Comment by jennytech** [comment]
@jasnow I don't know ,when i download rails I just choose the first one,How to change it 4.2.6?

**Comment by jasnow** [comment]
Nevermind about 4.2.6 - just thinking it would be simpler.

**Comment by jennytech** [comment]
@jasnow so rake db:migrate? I need run that first?then it would work?

**Comment by jasnow** [comment]
See pull request #2 that I just created.

**Comment by w-zengtao** [comment]
However, rails 5 rc 1 was on our production env when it was released . I thought that she does not know what 'migrate' is . And 'migrate' has its code .

**Comment by jennytech** [comment]
@jasnow so everything can work now?

**Comment by jennytech** [comment]
how did u make it green

**Comment by jasnow** [comment]
study the PR diffs
